name: Run Pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04  # Using stable image instead of ubuntu-24.04

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-html

      # Step 4: Run Pytest and generate reports
      - name: Run tests with Pytest
        run: |
          mkdir -p reports
          pytest --junitxml=test-results.xml --html=reports/report.html

      # Step 5: Upload test results
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3.1.0
        with:
          name: test-results
          path: |
            test-results.xml
            reports/report.html
